"""add account lockout fields to users

Revision ID: c7bd488f4839
Revises: dd0723c3586c
Create Date: 2026-09-05 16:40:00.000000

Hand-written rather than autogenerated: the shadow-SQLite-DB trick used
to generate the initial migration (see docs/architecture.md) produces
spurious NUMERIC->UUID "modify_type" noise for every existing column
when diffed a second time, because SQLite has no native UUID/ENUM types
to compare against. This migration only contains the two columns that
actually changed on the `User` model.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7bd488f4839"
down_revision: Union[str, Sequence[str], None] = "dd0723c3586c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "users",
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
    )
    # Drop the server_default now that existing rows are backfilled --
    # the application always supplies an explicit value going forward.
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("failed_login_attempts", server_default=None)


def downgrade() -> None:
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("locked_until")
        batch_op.drop_column("failed_login_attempts")
