"""initial schema

Revision ID: dd0723c3586c
Revises: 
Create Date: 2026-09-05 03:39:50.780474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0723c3586c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('is_newly_registered', sa.Boolean(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_table('ips',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('asn', sa.String(length=32), nullable=True),
    sa.Column('asn_org', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('approx_city', sa.String(length=128), nullable=True),
    sa.Column('approx_lat', sa.Float(), nullable=True),
    sa.Column('approx_lon', sa.Float(), nullable=True),
    sa.Column('geolocation_confidence', sa.String(length=16), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('is_known_malicious', sa.Boolean(), nullable=False),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ips_address'), 'ips', ['address'], unique=True)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='organization_status'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('report_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('template_body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key')
    )
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_table('graph_entities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_ref_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_entities_entity_type'), 'graph_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_graph_entities_organization_id'), 'graph_entities', ['organization_id'], unique=False)
    op.create_table('mailboxes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_mailboxes_organization_id'), 'mailboxes', ['organization_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_organization_id'), 'notification_events', ['organization_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('retain_days', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tags',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('full_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('is_shortened', sa.Boolean(), nullable=False),
    sa.Column('redirect_chain', sa.Text(), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('scanned_safely', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_normalized_url'), 'urls', ['normalized_url'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'SECURITY_ANALYST', 'INVESTIGATOR', 'SOC_ADMIN', 'ORG_ADMIN', 'PLATFORM_ADMIN', name='role_name'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'DISABLED', name='account_status'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_table('cases',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_analyst_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'TRIAGE', 'ANALYZING', 'UNDER_INVESTIGATION', 'ESCALATED', 'RESOLVED_MALICIOUS', 'RESOLVED_BENIGN', 'CLOSED', name='case_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_cases_organization_id'), 'cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cases_reporter_user_id'), 'cases', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('graph_relationships',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_relationships_organization_id'), 'graph_relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_graph_relationships_source_entity_id'), 'graph_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_graph_relationships_target_entity_id'), 'graph_relationships', ['target_entity_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEGRADED', name='analysis_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_case_id'), 'analysis_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_correlation_id'), 'analysis_runs', ['correlation_id'], unique=False)
    op.create_table('campaign_memberships',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_memberships_campaign_id'), 'campaign_memberships', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_memberships_case_id'), 'campaign_memberships', ['case_id'], unique=False)
    op.create_table('case_status_history',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_status_history_case_id'), 'case_status_history', ['case_id'], unique=False)
    op.create_table('case_tags',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'tag_id')
    )
    op.create_table('evidence_objects',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('RAW_EMAIL', 'ATTACHMENT', 'RENDERED_HTML', 'SCREENSHOT', 'REPORT_EXPORT', name='evidence_kind'), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=False),
    sa.Column('ingested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('ingest_method', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_objects_case_id'), 'evidence_objects', ['case_id'], unique=False)
    op.create_table('notes',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_case_id'), 'notes', ['case_id'], unique=False)
    op.create_table('analysis_findings',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_findings_analysis_run_id'), 'analysis_findings', ['analysis_run_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('raw_evidence_object_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=998), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('date_header', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_display_name', sa.String(length=255), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('reply_to_address', sa.String(length=255), nullable=True),
    sa.Column('return_path', sa.String(length=255), nullable=True),
    sa.Column('to_addresses', sa.Text(), nullable=True),
    sa.Column('cc_addresses', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_evidence_object_id'], ['evidence_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_case_id'), 'email_messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_email_messages_from_address'), 'email_messages', ['from_address'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=False)
    op.create_table('evidence_hashes',
    sa.Column('evidence_object_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.String(length=16), nullable=False),
    sa.Column('hex_digest', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_object_id'], ['evidence_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_hashes_evidence_object_id'), 'evidence_hashes', ['evidence_object_id'], unique=False)
    op.create_index(op.f('ix_evidence_hashes_hex_digest'), 'evidence_hashes', ['hex_digest'], unique=False)
    op.create_table('model_predictions',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('is_external_model', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_analysis_run_id'), 'model_predictions', ['analysis_run_id'], unique=False)
    op.create_table('reports',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('evidence_object_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_object_id'], ['evidence_objects.id'], ),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('confidence_band', sa.String(length=16), nullable=False),
    sa.Column('rationale_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_analysis_run_id'), 'risk_scores', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_case_id'), 'risk_scores', ['case_id'], unique=False)
    op.create_table('attachments',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('evidence_object_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('declared_mime_type', sa.String(length=128), nullable=True),
    sa.Column('detected_mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.Column('is_macro_enabled', sa.Boolean(), nullable=False),
    sa.Column('mime_type_mismatch', sa.Boolean(), nullable=False),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_object_id'], ['evidence_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_email_message_id'), 'attachments', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_attachments_sha256'), 'attachments', ['sha256'], unique=False)
    op.create_table('authentication_results',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('mechanism', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('raw_detail', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authentication_results_email_message_id'), 'authentication_results', ['email_message_id'], unique=False)
    op.create_table('email_headers',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_headers_email_message_id'), 'email_headers', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_email_headers_name'), 'email_headers', ['name'], unique=False)
    op.create_table('received_hops',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('hop_index', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('from_host', sa.String(length=255), nullable=True),
    sa.Column('from_ip', sa.String(length=64), nullable=True),
    sa.Column('by_host', sa.String(length=255), nullable=True),
    sa.Column('with_protocol', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_internal_relay', sa.Boolean(), nullable=False),
    sa.Column('parse_confidence', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_received_hops_email_message_id'), 'received_hops', ['email_message_id'], unique=False)
    op.create_index(op.f('ix_received_hops_from_ip'), 'received_hops', ['from_ip'], unique=False)
    op.create_table('sender_identities',
    sa.Column('email_message_id', sa.UUID(), nullable=False),
    sa.Column('claimed_display_name', sa.String(length=255), nullable=True),
    sa.Column('claimed_address', sa.String(length=255), nullable=True),
    sa.Column('claimed_organization_lookalike', sa.Boolean(), nullable=False),
    sa.Column('display_name_address_mismatch', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sender_identities_claimed_address'), 'sender_identities', ['claimed_address'], unique=False)
    op.create_index(op.f('ix_sender_identities_email_message_id'), 'sender_identities', ['email_message_id'], unique=False)
    op.create_table('ioc_records',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.Enum('DOMAIN', 'IP', 'URL', 'ATTACHMENT_HASH', 'EMAIL_ADDRESS', name='ioc_type'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=True),
    sa.Column('ip_id', sa.UUID(), nullable=True),
    sa.Column('url_id', sa.UUID(), nullable=True),
    sa.Column('attachment_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_in_case', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ioc_records_case_id'), 'ioc_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_ioc_records_value'), 'ioc_records', ['value'], unique=False)
    op.create_table('threat_intelligence_observations',
    sa.Column('ioc_record_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('is_synthetic_demo_data', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ioc_record_id'], ['ioc_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_observations_ioc_record_id'), 'threat_intelligence_observations', ['ioc_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_intelligence_observations_ioc_record_id'), table_name='threat_intelligence_observations')
    op.drop_table('threat_intelligence_observations')
    op.drop_index(op.f('ix_ioc_records_value'), table_name='ioc_records')
    op.drop_index(op.f('ix_ioc_records_case_id'), table_name='ioc_records')
    op.drop_table('ioc_records')
    op.drop_index(op.f('ix_sender_identities_email_message_id'), table_name='sender_identities')
    op.drop_index(op.f('ix_sender_identities_claimed_address'), table_name='sender_identities')
    op.drop_table('sender_identities')
    op.drop_index(op.f('ix_received_hops_from_ip'), table_name='received_hops')
    op.drop_index(op.f('ix_received_hops_email_message_id'), table_name='received_hops')
    op.drop_table('received_hops')
    op.drop_index(op.f('ix_email_headers_name'), table_name='email_headers')
    op.drop_index(op.f('ix_email_headers_email_message_id'), table_name='email_headers')
    op.drop_table('email_headers')
    op.drop_index(op.f('ix_authentication_results_email_message_id'), table_name='authentication_results')
    op.drop_table('authentication_results')
    op.drop_index(op.f('ix_attachments_sha256'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_email_message_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_risk_scores_case_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_analysis_run_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_model_predictions_analysis_run_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_evidence_hashes_hex_digest'), table_name='evidence_hashes')
    op.drop_index(op.f('ix_evidence_hashes_evidence_object_id'), table_name='evidence_hashes')
    op.drop_table('evidence_hashes')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_from_address'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_case_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_analysis_findings_analysis_run_id'), table_name='analysis_findings')
    op.drop_table('analysis_findings')
    op.drop_index(op.f('ix_notes_case_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_evidence_objects_case_id'), table_name='evidence_objects')
    op.drop_table('evidence_objects')
    op.drop_table('case_tags')
    op.drop_index(op.f('ix_case_status_history_case_id'), table_name='case_status_history')
    op.drop_table('case_status_history')
    op.drop_index(op.f('ix_campaign_memberships_case_id'), table_name='campaign_memberships')
    op.drop_index(op.f('ix_campaign_memberships_campaign_id'), table_name='campaign_memberships')
    op.drop_table('campaign_memberships')
    op.drop_index(op.f('ix_analysis_runs_correlation_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_case_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_graph_relationships_target_entity_id'), table_name='graph_relationships')
    op.drop_index(op.f('ix_graph_relationships_source_entity_id'), table_name='graph_relationships')
    op.drop_index(op.f('ix_graph_relationships_organization_id'), table_name='graph_relationships')
    op.drop_table('graph_relationships')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_reporter_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_organization_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_urls_normalized_url'), table_name='urls')
    op.drop_table('urls')
    op.drop_table('tags')
    op.drop_table('role_permissions')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_notification_events_organization_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_mailboxes_organization_id'), table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_graph_entities_organization_id'), table_name='graph_entities')
    op.drop_index(op.f('ix_graph_entities_entity_type'), table_name='graph_entities')
    op.drop_table('graph_entities')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('roles')
    op.drop_table('report_templates')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_ips_address'), table_name='ips')
    op.drop_table('ips')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
